### ISSUE TITLE
EOFError (end of file reached):  app/controllers/contacts_controller.rb:5:in `create' 

### ISSUE THREAD

**Issue by MarinoGit** [plataformatec/mail_form#49]
Hi,

I´m using mail_form in a staging environment and I´m having this error:
```
<br />  
Oct 22 07:27:47 XXXXXX-stagging app/web.1:  ----==_mimepart_580b776152614_73fbd91d1333045d2--  
Oct 22 07:27:47 XXXXXX-stagging app/web.1:  Completed 500 Internal Server Error in 5384ms 
Oct 22 07:27:47 XXXXXX-stagging app/web.1:  EOFError (end of file reached): 
Oct 22 07:27:47 XXXXXX-stagging app/web.1:    app/controllers/contacts_controller.rb:5:in `create' 
```
In my staging.rb I have this SMTP configuration:

```
config.action_mailer.raise_delivery_errors = true
    config.action_mailer.perform_deliveries = true
    config.action_mailer.asset_host = "https://XXXXXXXXX-stagging.herokuapp.com"
    config.action_mailer.default_url_options = { :host =>  ENV['HOST_PRO']}
    # Action Mailer
    config.action_mailer.smtp_settings = {
      :address              => "smtp.zoho.com",
      :port                 => 465,
      :user_name            => ENV['ZOHO_USERNAME_PRO'],
      :password             => ENV['ZOHO_PASSWORD_PRO'],
      :authentication       => :login,
      :ssl                  => true,
      :tls                  => true
    }
```

I´m using this ZOHO_USERNAME_PRO as the :to email in contacts.rb

```
# Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Consulta de #{nombre} - #{email}",
      :to => "noreply@XXXXXXXX.com",
      :from => %("#{nombre}" <#{email}>)
    }
  end
```
My app is Rails 4.0.2 and fails on Heroku and the rest of mails works fine. 

Thanks for any help

**Comment by nashby** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by MarinoGit** [comment]
Hi, 

I think the problem is this line:
```
#config/environments/staging.rb
config.action_mailer.smtp_settings = {
      :return_response      => true,
      :address              => "smtp.zoho.com",
      :port                 => 465,
      **:user_name            => ENV['ZOHO_USERNAME_PRO'],**
      :password             => ENV['ZOHO_PASSWORD_PRO'],
      :authentication       => :login,
      :ssl                  => true,
      :tls                  => true
    }
```

and this line:


```
#app/model/contact.rb
# Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Consulta de #{nombre} - #{email}",
      :to => ENV['ZOHO_USERNAME_PRO'],
      :from => **ENV['ZOHO_USERNAME_PRO']**
    }
  end
```

In my configuration, I have setted the user_name or From and Zoho is refusing mail where from is not equal ENV['ZOHO_USERNAME_PRO']

While is an internal mail is not any problem to use a internal from address. Another solution could be maintain config.action_mailer.smtp_settings without configuring 'user_name' and set it up as required 

Please, close the issue, is a external probem

Thanks for your help and the good job in this and other gems.

Marino

**Comment by nashby** [comment]
@MarinoGit thanks!
